// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ledger/v1/ledger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BudgetAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit         float32                `protobuf:"fixed32,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetAddRequest) Reset() {
	*x = BudgetAddRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetAddRequest) ProtoMessage() {}

func (x *BudgetAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetAddRequest.ProtoReflect.Descriptor instead.
func (*BudgetAddRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *BudgetAddRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BudgetAddRequest) GetLimit() float32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BudgetGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetGetRequest) Reset() {
	*x = BudgetGetRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetGetRequest) ProtoMessage() {}

func (x *BudgetGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetGetRequest.ProtoReflect.Descriptor instead.
func (*BudgetGetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetGetRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type BudgetGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit         float32                `protobuf:"fixed32,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetGetResponse) Reset() {
	*x = BudgetGetResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetGetResponse) ProtoMessage() {}

func (x *BudgetGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetGetResponse.ProtoReflect.Descriptor instead.
func (*BudgetGetResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *BudgetGetResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BudgetGetResponse) GetLimit() float32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BudgetGetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budgets       []*BudgetGetResponse   `protobuf:"bytes,1,rep,name=budgets,proto3" json:"budgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetGetListResponse) Reset() {
	*x = BudgetGetListResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetGetListResponse) ProtoMessage() {}

func (x *BudgetGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetGetListResponse.ProtoReflect.Descriptor instead.
func (*BudgetGetListResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *BudgetGetListResponse) GetBudgets() []*BudgetGetResponse {
	if x != nil {
		return x.Budgets
	}
	return nil
}

type TransactionAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionAddRequest) Reset() {
	*x = TransactionAddRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionAddRequest) ProtoMessage() {}

func (x *TransactionAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionAddRequest.ProtoReflect.Descriptor instead.
func (*TransactionAddRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionAddRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionAddRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TransactionAddRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionAddRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type TransactionAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionAddResponse) Reset() {
	*x = TransactionAddResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionAddResponse) ProtoMessage() {}

func (x *TransactionAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionAddResponse.ProtoReflect.Descriptor instead.
func (*TransactionAddResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionAddResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TransactionGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionGetRequest) Reset() {
	*x = TransactionGetRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionGetRequest) ProtoMessage() {}

func (x *TransactionGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionGetRequest.ProtoReflect.Descriptor instead.
func (*TransactionGetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TransactionGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionGetResponse) Reset() {
	*x = TransactionGetResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionGetResponse) ProtoMessage() {}

func (x *TransactionGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionGetResponse.ProtoReflect.Descriptor instead.
func (*TransactionGetResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionGetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionGetResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionGetResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TransactionGetResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionGetResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type TransactionGetListResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transactions  []*TransactionGetResponse `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionGetListResponse) Reset() {
	*x = TransactionGetListResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionGetListResponse) ProtoMessage() {}

func (x *TransactionGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionGetListResponse.ProtoReflect.Descriptor instead.
func (*TransactionGetListResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionGetListResponse) GetTransactions() []*TransactionGetResponse {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/ledger.proto\x12\tledger.v1\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x10BudgetAddRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x02R\x05limit\".\n" +
	"\x10BudgetGetRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"E\n" +
	"\x11BudgetGetResponse\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x02R\x05limit\"O\n" +
	"\x15BudgetGetListResponse\x126\n" +
	"\abudgets\x18\x01 \x03(\v2\x1c.ledger.v1.BudgetGetResponseR\abudgets\"\x81\x01\n" +
	"\x15TransactionAddRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\"(\n" +
	"\x16TransactionAddResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"'\n" +
	"\x15TransactionGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x92\x01\n" +
	"\x16TransactionGetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\"c\n" +
	"\x1aTransactionGetListResponse\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.ledger.v1.TransactionGetResponseR\ftransactions2\xe2\x03\n" +
	"\rLedgerService\x12@\n" +
	"\tBudgetAdd\x12\x1b.ledger.v1.BudgetAddRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\tBudgetGet\x12\x1b.ledger.v1.BudgetGetRequest\x1a\x1c.ledger.v1.BudgetGetResponse\x12G\n" +
	"\vBudgetsList\x12\x16.google.protobuf.Empty\x1a .ledger.v1.BudgetGetListResponse\x12U\n" +
	"\x0eTransactionAdd\x12 .ledger.v1.TransactionAddRequest\x1a!.ledger.v1.TransactionAddResponse\x12U\n" +
	"\x0eTransactionGet\x12 .ledger.v1.TransactionGetRequest\x1a!.ledger.v1.TransactionGetResponse\x12P\n" +
	"\x0fTransactionList\x12\x16.google.protobuf.Empty\x1a%.ledger.v1.TransactionGetListResponseB\x1fZ\x1dgateway/internal/pb/ledger/v1b\x06proto3"

var (
	file_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_ledger_v1_ledger_proto_rawDescData []byte
)

func file_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_ledger_v1_ledger_proto_rawDescData
}

var file_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ledger_v1_ledger_proto_goTypes = []any{
	(*BudgetAddRequest)(nil),           // 0: ledger.v1.BudgetAddRequest
	(*BudgetGetRequest)(nil),           // 1: ledger.v1.BudgetGetRequest
	(*BudgetGetResponse)(nil),          // 2: ledger.v1.BudgetGetResponse
	(*BudgetGetListResponse)(nil),      // 3: ledger.v1.BudgetGetListResponse
	(*TransactionAddRequest)(nil),      // 4: ledger.v1.TransactionAddRequest
	(*TransactionAddResponse)(nil),     // 5: ledger.v1.TransactionAddResponse
	(*TransactionGetRequest)(nil),      // 6: ledger.v1.TransactionGetRequest
	(*TransactionGetResponse)(nil),     // 7: ledger.v1.TransactionGetResponse
	(*TransactionGetListResponse)(nil), // 8: ledger.v1.TransactionGetListResponse
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_ledger_v1_ledger_proto_depIdxs = []int32{
	2, // 0: ledger.v1.BudgetGetListResponse.budgets:type_name -> ledger.v1.BudgetGetResponse
	7, // 1: ledger.v1.TransactionGetListResponse.transactions:type_name -> ledger.v1.TransactionGetResponse
	0, // 2: ledger.v1.LedgerService.BudgetAdd:input_type -> ledger.v1.BudgetAddRequest
	1, // 3: ledger.v1.LedgerService.BudgetGet:input_type -> ledger.v1.BudgetGetRequest
	9, // 4: ledger.v1.LedgerService.BudgetsList:input_type -> google.protobuf.Empty
	4, // 5: ledger.v1.LedgerService.TransactionAdd:input_type -> ledger.v1.TransactionAddRequest
	6, // 6: ledger.v1.LedgerService.TransactionGet:input_type -> ledger.v1.TransactionGetRequest
	9, // 7: ledger.v1.LedgerService.TransactionList:input_type -> google.protobuf.Empty
	9, // 8: ledger.v1.LedgerService.BudgetAdd:output_type -> google.protobuf.Empty
	2, // 9: ledger.v1.LedgerService.BudgetGet:output_type -> ledger.v1.BudgetGetResponse
	3, // 10: ledger.v1.LedgerService.BudgetsList:output_type -> ledger.v1.BudgetGetListResponse
	5, // 11: ledger.v1.LedgerService.TransactionAdd:output_type -> ledger.v1.TransactionAddResponse
	7, // 12: ledger.v1.LedgerService.TransactionGet:output_type -> ledger.v1.TransactionGetResponse
	8, // 13: ledger.v1.LedgerService.TransactionList:output_type -> ledger.v1.TransactionGetListResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ledger_v1_ledger_proto_init() }
func file_ledger_v1_ledger_proto_init() {
	if File_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_ledger_v1_ledger_proto = out.File
	file_ledger_v1_ledger_proto_goTypes = nil
	file_ledger_v1_ledger_proto_depIdxs = nil
}
