// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: ledger/v1/ledger.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_BudgetAdd_FullMethodName       = "/ledger.v1.LedgerService/BudgetAdd"
	LedgerService_BudgetGet_FullMethodName       = "/ledger.v1.LedgerService/BudgetGet"
	LedgerService_BudgetsList_FullMethodName     = "/ledger.v1.LedgerService/BudgetsList"
	LedgerService_TransactionAdd_FullMethodName  = "/ledger.v1.LedgerService/TransactionAdd"
	LedgerService_TransactionGet_FullMethodName  = "/ledger.v1.LedgerService/TransactionGet"
	LedgerService_TransactionList_FullMethodName = "/ledger.v1.LedgerService/TransactionList"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	BudgetAdd(ctx context.Context, in *BudgetAddRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BudgetGet(ctx context.Context, in *BudgetGetRequest, opts ...grpc.CallOption) (*BudgetGetResponse, error)
	BudgetsList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BudgetGetListResponse, error)
	TransactionAdd(ctx context.Context, in *TransactionAddRequest, opts ...grpc.CallOption) (*TransactionAddResponse, error)
	TransactionGet(ctx context.Context, in *TransactionGetRequest, opts ...grpc.CallOption) (*TransactionGetResponse, error)
	TransactionList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TransactionGetListResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) BudgetAdd(ctx context.Context, in *BudgetAddRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LedgerService_BudgetAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) BudgetGet(ctx context.Context, in *BudgetGetRequest, opts ...grpc.CallOption) (*BudgetGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetGetResponse)
	err := c.cc.Invoke(ctx, LedgerService_BudgetGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) BudgetsList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BudgetGetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetGetListResponse)
	err := c.cc.Invoke(ctx, LedgerService_BudgetsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) TransactionAdd(ctx context.Context, in *TransactionAddRequest, opts ...grpc.CallOption) (*TransactionAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionAddResponse)
	err := c.cc.Invoke(ctx, LedgerService_TransactionAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) TransactionGet(ctx context.Context, in *TransactionGetRequest, opts ...grpc.CallOption) (*TransactionGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionGetResponse)
	err := c.cc.Invoke(ctx, LedgerService_TransactionGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) TransactionList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TransactionGetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionGetListResponse)
	err := c.cc.Invoke(ctx, LedgerService_TransactionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	BudgetAdd(context.Context, *BudgetAddRequest) (*emptypb.Empty, error)
	BudgetGet(context.Context, *BudgetGetRequest) (*BudgetGetResponse, error)
	BudgetsList(context.Context, *emptypb.Empty) (*BudgetGetListResponse, error)
	TransactionAdd(context.Context, *TransactionAddRequest) (*TransactionAddResponse, error)
	TransactionGet(context.Context, *TransactionGetRequest) (*TransactionGetResponse, error)
	TransactionList(context.Context, *emptypb.Empty) (*TransactionGetListResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) BudgetAdd(context.Context, *BudgetAddRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BudgetAdd not implemented")
}
func (UnimplementedLedgerServiceServer) BudgetGet(context.Context, *BudgetGetRequest) (*BudgetGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BudgetGet not implemented")
}
func (UnimplementedLedgerServiceServer) BudgetsList(context.Context, *emptypb.Empty) (*BudgetGetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BudgetsList not implemented")
}
func (UnimplementedLedgerServiceServer) TransactionAdd(context.Context, *TransactionAddRequest) (*TransactionAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionAdd not implemented")
}
func (UnimplementedLedgerServiceServer) TransactionGet(context.Context, *TransactionGetRequest) (*TransactionGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionGet not implemented")
}
func (UnimplementedLedgerServiceServer) TransactionList(context.Context, *emptypb.Empty) (*TransactionGetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionList not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_BudgetAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BudgetAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).BudgetAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_BudgetAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).BudgetAdd(ctx, req.(*BudgetAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_BudgetGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BudgetGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).BudgetGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_BudgetGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).BudgetGet(ctx, req.(*BudgetGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_BudgetsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).BudgetsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_BudgetsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).BudgetsList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_TransactionAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).TransactionAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_TransactionAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).TransactionAdd(ctx, req.(*TransactionAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_TransactionGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).TransactionGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_TransactionGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).TransactionGet(ctx, req.(*TransactionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_TransactionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).TransactionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_TransactionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).TransactionList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BudgetAdd",
			Handler:    _LedgerService_BudgetAdd_Handler,
		},
		{
			MethodName: "BudgetGet",
			Handler:    _LedgerService_BudgetGet_Handler,
		},
		{
			MethodName: "BudgetsList",
			Handler:    _LedgerService_BudgetsList_Handler,
		},
		{
			MethodName: "TransactionAdd",
			Handler:    _LedgerService_TransactionAdd_Handler,
		},
		{
			MethodName: "TransactionGet",
			Handler:    _LedgerService_TransactionGet_Handler,
		},
		{
			MethodName: "TransactionList",
			Handler:    _LedgerService_TransactionList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger/v1/ledger.proto",
}
